package com.example.aitranslators


var languages = listOf(
    "Detect Language",
    "English",
    "German",
    "French",
    "Spanish",
    "Persian",
    "Arabic",
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Armenian",
    "Azerbaijani",
    "Assamese",
    "Aymara",
    "Bambara",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bhojpuri",
    "Burmese",
    "Bosnian",
    "Bulgarian",
    "Cebuano",
    "Chichewa",
    "Chinese",
    "Danish",
    "Dhivehi",
    "Dogri",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Filipino",
    "Finnish",
    "Frisian",
    "Galician",
    "Georgian",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Igbo",
    "Ilokano",
    "Indonesian",
    "Irish",
    "Icelandic",
    "Italian",
    "Japanese",
    "Javanese",
    "Yiddish",
    "Kannada",
    "Kazakh",
    "Catalan",
    "Khmer",
    "Kinyarwanda",
    "Kyrgyz",
    "Konkani",
    "Korean",
    "Corsican",
    "Krio",
    "Croatian",
    "Kurdish",
    "Lao",
    "Latin",
    "Latvian",
    "Lingala",
    "Lithuanian",
    "Luganda",
    "Luxembourgish",
    "Maithili",
    "Malagasy",
    "Malayalam",
    "Malaysian",
    "Maltese",
    "Maori",
    "Marathi",
    "Macedonian",
    "Meitei (Manipuri)",
    "Mizo",
    "Mongolian",
    "Nepali",
    "Dutch",
    "Norwegian",
    "Odia (Oriya)",
    "Oromo",
    "Pashto",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romanian",
    "Russian",
    "Samoan",
    "Sanskrit",
    "Scottish Gaelic",
    "Swedish",
    "Sepedi",
    "Serbian",
    "Sesotho",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "Sundanese",
    "Swahili",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tigrinya",
    "Czech",
    "Tsonga",
    "Turkish",
    "Turkmen",
    "Twi",
    "Uighur",
    "Ukrainian",
    "Hungarian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Welsh",
    "Xhosa",
    "Yoruba",
    "Zulu"
)

 val languageMap = mapOf(
     "Detect Language" to null,
     "English" to "en",
     "German" to "de",
     "French" to "fr",
     "Spanish" to "es",
     "Persian" to "fa",
     "Arabic" to "ar",
     "Afrikaans" to "af",
     "Albanian" to "sq",
     "Amharic" to "am",
     "Armenian" to "hy",
     "Azerbaijani" to "az",
     "Assamese" to "as",
     "Aymara" to "ay",
     "Bambara" to "bm",
     "Basque" to "eu",
     "Belarusian" to "be",
     "Bengali" to "bn",
     "Bhojpuri" to "bh",
     "Burmese" to "my",
     "Bosnian" to "bs",
     "Bulgarian" to "bg",
     "Cebuano" to "ceb",
     "Chichewa" to "ny",
     "Chinese" to "zh",
     "Danish" to "da",
     "Dhivehi" to "dv",
     "Dogri" to "doi",
     "Esperanto" to "eo",
     "Estonian" to "et",
     "Ewe" to "ee",
     "Filipino" to "tl",
     "Finnish" to "fi",
     "Frisian" to "fy",
     "Galician" to "gl",
     "Georgian" to "ka",
     "Greek" to "el",
     "Guarani" to "gn",
     "Gujarati" to "gu",
     "Haitian" to "ht",
     "Hausa" to "ha",
     "Hawaiian" to "haw",
     "Hebrew" to "he",
     "Hindi" to "hi",
     "Hmong" to "hmn",
     "Igbo" to "ig",
     "Ilokano" to "ilo",
     "Indonesian" to "id",
     "Irish" to "ga",
     "Icelandic" to "is",
     "Italian" to "it",
     "Japanese" to "ja",
     "Javanese" to "jv",
     "Yiddish" to "yi",
     "Kannada" to "kn",
     "Kazakh" to "kk",
     "Catalan" to "ca",
     "Khmer" to "km",
     "Kinyarwanda" to "rw",
     "Kyrgyz" to "ky",
     "Konkani" to "kok",
     "Korean" to "ko",
     "Corsican" to "co",
     "Krio" to "kri",
     "Croatian" to "hr",
     "Kurdish" to "ku",
     "Lao" to "lo",
     "Latin" to "la",
     "Latvian" to "lv",
     "Lingala" to "ln",
     "Lithuanian" to "lt",
     "Luganda" to "lg",
     "Luxembourgish" to "lb",
     "Maithili" to "mai",
     "Malagasy" to "mg",
     "Malayalam" to "ml",
     "Malaysian" to "ms",
     "Maltese" to "mt",
     "Maori" to "mi",
     "Marathi" to "mr",
     "Macedonian" to "mk",
     "Meitei (Manipuri)" to "mni",
     "Mizo" to "lus",
     "Mongolian" to "mn",
     "Nepali" to "ne",
     "Dutch" to "nl",
     "Norwegian" to "no",
     "Odia (Oriya)" to "or",
     "Oromo" to "om",
     "Pashto" to "ps",
     "Polish" to "pl",
     "Portuguese" to "pt",
     "Punjabi" to "pa",
     "Quechua" to "qu",
     "Romanian" to "ro",
     "Russian" to "ru",
     "Samoan" to "sm",
     "Sanskrit" to "sa",
     "Scottish Gaelic" to "gd",
     "Swedish" to "sv",
     "Sepedi" to "nso",
     "Serbian" to "sr",
     "Sesotho" to "st",
     "Shona" to "sn",
     "Sindhi" to "sd",
     "Sinhala" to "si",
     "Slovak" to "sk",
     "Slovenian" to "sl",
     "Somali" to "so",
     "Sundanese" to "su",
     "Swahili" to "sw",
     "Tajik" to "tg",
     "Tamil" to "ta",
     "Tatar" to "tt",
     "Telugu" to "te",
     "Thai" to "th",
     "Tigrinya" to "ti",
     "Czech" to "cs",
     "Tsonga" to "ts",
     "Turkish" to "tr",
     "Turkmen" to "tk",
     "Twi" to "tw",
     "Uighur" to "ug",
     "Ukrainian" to "uk",
     "Hungarian" to "hu",
     "Urdu" to "ur",
     "Uzbek" to "uz",
     "Vietnamese" to "vi",
     "Welsh" to "cy",
     "Xhosa" to "xh",
     "Yoruba" to "yo",
     "Zulu" to "zu",
)



val languageMapReverse = languageMap.entries.associateBy({ it.value }, { it.key })

